/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewbarbearia;

import Controller.AgendaController;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author emanu
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;
    public Object getJComboBoxCliente;
    private Object JComboBoxCliente;
    public Object getJComboBoxServico;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller =new AgendaController (this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonagenda = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        jTextFieldhora = new javax.swing.JTextField();
        jTextFielddata = new javax.swing.JTextField();
        jTextFieldvalor = new javax.swing.JTextField();
        jTextFieldid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaobservacao = new javax.swing.JTextArea();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabelobservacao = new javax.swing.JLabel();
        jLabelhora = new javax.swing.JLabel();
        jLabeldata = new javax.swing.JLabel();
        jLabelvalor = new javax.swing.JLabel();
        jLabelServicos = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelAgenda = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonagenda.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButtonagenda.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jToggleButtonagenda.setForeground(new java.awt.Color(51, 255, 51));
        jToggleButtonagenda.setText("AGENDA");
        jToggleButtonagenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonagendaActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonagenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 371, 470, 60));

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CLIENTE", "SERVIÇO", "VALOR R$", "DATA", "HORA", "OBSERVAÇÃO"
            }
        ));
        jScrollPane2.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 1040, 100));
        getContentPane().add(jTextFieldhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 190, -1));
        getContentPane().add(jTextFielddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 190, -1));

        jTextFieldvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvalorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 190, -1));

        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 170, -1));

        jTextAreaobservacao.setColumns(20);
        jTextAreaobservacao.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextAreaobservacao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaobservacao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 470, 240));

        jComboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxServicoItemStateChanged(evt);
            }
        });
        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, -1));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, -1));

        jLabelobservacao.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabelobservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelobservacao.setText("OBSERVAÇÃO:");
        getContentPane().add(jLabelobservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 150, -1));

        jLabelhora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelhora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelhora.setText("HORA");
        getContentPane().add(jLabelhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jLabeldata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeldata.setForeground(new java.awt.Color(255, 255, 255));
        jLabeldata.setText("DATA");
        getContentPane().add(jLabeldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabelvalor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelvalor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelvalor.setText("VALOR R$");
        getContentPane().add(jLabelvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabelServicos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelServicos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServicos.setText("SERVIÇOS");
        getContentPane().add(jLabelServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabelCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("CLIENTE");
        getContentPane().add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jLabelId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabelAgenda.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabelAgenda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAgenda.setText("AGENDA");
        getContentPane().add(jLabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 80, 180, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, -1, 750));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/AgendaFundo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1287, 989));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jTextFieldvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvalorActionPerformed

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jComboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxServicoItemStateChanged
        this.controller.atualizaValor();
    }//GEN-LAST:event_jComboBoxServicoItemStateChanged

    private void jToggleButtonagendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonagendaActionPerformed
       this.controller.atualizarTabela();
    }//GEN-LAST:event_jToggleButtonagendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Agenda().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelServicos;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JLabel jLabelhora;
    private javax.swing.JLabel jLabelobservacao;
    private javax.swing.JLabel jLabelvalor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaobservacao;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFieldhora;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldvalor;
    private javax.swing.JToggleButton jToggleButtonagenda;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
      this.controller.atualizarTabela();
      this.controller.atualizaCliente();
      this.controller.atualizaServico();
      this.controller.atualizaValor();

    }

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }

    public JComboBox<String> getjComboBoxCliente() {
        return jComboBoxCliente;
    }

    public void setjComboBoxCliente(JComboBox<String> jComboBoxCliente) {
        this.jComboBoxCliente = jComboBoxCliente;
    }

    public JComboBox<String> getjComboBoxServico() {
        return jComboBoxServico;
    }

    public void setjComboBoxServico(JComboBox<String> jComboBoxServico) {
        this.jComboBoxServico = jComboBoxServico;
    }

    public Object getJComboBoxCliente() {
    return this.JComboBoxCliente;
    }

    public JTextField getjTextFieldvalor() {
        return jTextFieldvalor;
    }

    public void setjTextFieldvalor(JTextField jTextFieldvalor) {
        this.jTextFieldvalor = jTextFieldvalor;
    }

    public JTextArea getjTextAreaobservacao() {
        return jTextAreaobservacao;
    }

    public void setjTextAreaobservacao(JTextArea jTextAreaobservacao) {
        this.jTextAreaobservacao = jTextAreaobservacao;
    }

    public JTextField getjTextFielddata() {
        return jTextFielddata;
    }

    public void setjTextFielddata(JTextField jTextFielddata) {
        this.jTextFielddata = jTextFielddata;
    }

    public JTextField getjTextFieldhora() {
        return jTextFieldhora;
    }

    public void setjTextFieldhora(JTextField jTextFieldhora) {
        this.jTextFieldhora = jTextFieldhora;
    }

    public JTextField getjTextFieldid() {
        return jTextFieldid;
    }

    public void setjTextFieldid(JTextField jTextFieldid) {
        this.jTextFieldid = jTextFieldid;
    }

  
    }

   

      


   
       
    

   
    

